name: build snapshot release
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.0
      - name: setup jdk 8.0
        uses: actions/setup-java@v4.0.0
        with:
          distribution: adopt
          java-version: 8.0
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      # 第一次构建
      - name: build
        id: build_1
        run: ./gradlew clean taboolibBuildApi -PDeleteCode
      # 第二次构建
      - name: build (retry 1)
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew clean taboolibBuildApi -PDeleteCode
      # 第三次构建
      - name: build (retry 2)
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew clean taboolibBuildApi -PDeleteCode
      # 第四次构建
      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew clean taboolibBuildApi -PDeleteCode
      # 上传构建文件
      - name: capture build artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TheTrackOfShadow_Snapshot_${{ github.run_number }}
          path: build/libs/
